eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/requests_db
    username: postgres
    password: password
  initialization-mode: always
  jpa:
    hibernate:
     ddl-auto: none